### PR TITLE
Added context switching

### LINKED ISSUE #3: Destaticify JS frontend
Most of the javascript code to hold the snapshot state is static. We need to change this to a more dynamic implementation, allowing us to switch between multiple contexts.

We could use a framework like React, but I am not that versed in front end or web dev to know if this is overkill or not.

### PR DESCRIPTION
**Pull request by Nydauron**
Adds the ability to swap the viewmodel to different contexts (e.g. program 1 and program 2)

### CODE REVIEW

**Review by Nydauron — COMMENTED** [review]
Looks good! Some things ive encountered:

- Breakpoints are not remembered after the context has been swapped and then is swapped again back to the original context (e.g. I set a breakpoint on program 2, swap back to program 1, then swap back to program 2, the line that I added the breakpoint is not bolded). Note: the breakpoint still exists, but its just not being rendered on the frontend.
- Clicking reset while on program 2 seems to reset the context to program 1. Ideally, this should not be changed. Becuse now it is out of sync with the text segment and data segments.
- User stack does not seem to be getting updated in program 2. (it seems like as it it is using program 1's stack pointer)

**Comment by Nydauron** [comment]
The first two bugs have been fixed. The third one still persists.

The example below: `fibonacci.s` does stack allocation due to the recursive nature of the Fibonacci function. `test_core.s` does not really do that much stack allocation in comparison to `fibonacci.s`. So, we should see less activity, but we instead see program 1's stack
image

**Comment by Nydauron** [comment]
Nice that bug is fixed!

I found another bug (maybe due to that fix) where I get double lines in the user stack. I was able to replicate it by switching to the Fibonacci program while it was running.
image

**Comment by alanzyt311** [comment]
That's a weird bug. Sometimes I got the double line and sometimes it just behave normally. Will take look at it.

**Pull request merged**
